DROP TABLE DEVELOPER;
DROP TABLE PROJECTS;

CREATE TABLE PROJECTS(
	PROJECT_ID NUMBER(10) NOT NULL,
	CLIENT_ID NUMBER(10),
	P_NAME VARCHAR(50)
);
CREATE TABLE DEVELOPER(
	DEVELOPER_ID NUMBER(10) NOT NULL,
	PROJECT_ID NUMBER(10),
	D_NAME VARCHAR(10)
);

ALTER TABLE PROJECTS add constraint pkpr primary key(PROJECT_ID);
ALTER TABLE DEVELOPER add constraint pkdv primary key(DEVELOPER_ID);
ALTER TABLE DEVELOPER add constraint fkdv foreign key(PROJECT_ID) references PROJECTS(PROJECT_ID) on delete cascade;

INSERT INTO PROJECTS VALUES(31, 11, 'Simple-DATABASE');
INSERT INTO PROJECTS VALUES(32, 12, 'Desktop-App');

INSERT INTO DEVELOPER VALUES(41, 31, 'A');
INSERT INTO DEVELOPER VALUES(42, 32, 'B');

SELECT * FROM tab;

DESCRIBE PROJECTS;
DESCRIBE DEVELOPER;

SELECT * FROM PROJECTS;
SELECT * FROM DEVELOPER;


SELECT p.P_NAME, d.D_NAME from PROJECTS p NATURAL JOIN DEVELOPER d;